print("What is your name?")
name = input()
print("What is your age?")
age = input()
print("What is your speed?")
speed = input()
print("What is your species type?")
species = input()
print("What is your intelligence rating?")
intelligence = input()
print("Are you alive?")
alive = input()
print("What is your origin?")
origin = input()
print("What is your strenght?")
strenght = input()
print("What is your experience?")
experience = input()
print("How much coins do you have?")
coins = input()

print("\n")
print("Hello " + name)
print("Your stats are:")
print("\n")
print("Name: " + name)
print("Speed: " + str(speed))
print("Species type: " + species)
print("Intelligence rating = " + str(intelligence))
print("Age = " + str(age))
print("Alive = " + alive)
print("Origin: " + origin)
print("Strenght: " + str(strenght))
print("Experience: " + str(experience))
print("Coins: " + str(coins) + "k")
xe = input()
