print("What is your name")
name = input()
print("\n")
print("Hello " + name)
print("Your stats are:")
print("\n")
print("Name: " + name)
print("Stanima: 3583")
print("Species type: Human")
print("Intelligence rating = 114,76")
print("Armed = false")
print("Alive = true")
print("Origin: Andromeda Galaxy")
print("Strenght: 30")
print("Experience: 4593")

dontclose = input()
