print("What is your name")
name = input()
print("\n")
print("Hello " + name)
print("Your stats are:")
print("\n")
print("Name: " + name)
print("Speed: 143")
print("Species type: Human")
print("Intelligence rating = 114,76")
print("Age = 17")
print("Alive = true")
print("Origin: Castricum")
print("Strenght: 30")
print("Experience: 4593")
print("Coins: 3,76k")
xe = input()
